### ISSUE TITLE
SaveProjectAs error in example

### ISSUE THREAD

**Issue by ArneRichter** [WildGums/Orc.ProjectManagement#152]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component
Orc.ProjectManagement
What component is this issue occurring in?
Orc.ProjectManagement.Example.NET/ViewModels/MainWindowViewModel.cs

Find a copy and paste error in line 162 in function "OnSaveProjectAsExecuteAsync()"
At the moment you save "_openFileService.FileName" 
it should be "_saveFileService.FileName"
So you can change it to 
"                await _projectManager.SaveAsync(_saveFileService.FileName).ConfigureAwait(false);"

**Comment by GeertvanHorrik** [comment]
Pinging @Averus-a

**Comment by Averus-a** [comment]
@GeertvanHorrik 
I made a small fix, example is correct now

**Comment by GeertvanHorrik** [comment]
@ArneRichter thanks for reporting
@Averus-a thanks for fixing
