### ISSUE TITLE
ProjectWriter.cs(17,18,17,31): error CS7069: Reference to type 'INotifyDataErrorInfo' claims it is defined in 'Catel.Core', but it could not be found

### ISSUE THREAD

**Issue by Aitania** [WildGums/Orc.ProjectManagement#3]
Hallo Geert,
I have a problem implementing the ProjectWriter class
    public class ProjectWriter : ProjectWriterBase<InfoModelBase>
"ProjectWriter.cs(17,18,17,31): error CS7069: Reference to type 'INotifyDataErrorInfo' claims it is defined in 'Catel.Core', but it could not be found"
My Catel.Core Runtime Version: v4.0.30319. Version: 4.5.00

best Regards
Michael

**Comment by GeertvanHorrik** [comment]
Are you maybe referencing a 4.0 version of Orc.ProjectManagement / Catel in a 4.5 / 4.6 project?

**Comment by Aitania** [comment]
Yes... That was !

Thank you.
