### ISSUE TITLE
Orchestra, LogViewer and Orc.ProjectManagement. MarkAsDirty, Is Dirty and co...

### ISSUE THREAD

**Issue by Aitania** [WildGums/Orc.ProjectManagement#4]
### Feature description

Hallo,
I use Orchestra as Template for my Application.
I embed Orc.ProjectManagement to manage/control my data saved in a file as xml.
I have read a lot about the CancelAsync, SaveAsync, CloseAsync in Catel. 
Orchestra uses the ApplicationExitCommandContainer to exit the Application.
I want to notify my Project that is Dirty (Mark as Dirty) and check later on and ask the user 
about save it... 
Is there a good way to ask the VMs if they are Dirty (HasDirtyModel)?
How i cann call         

```
private void OnCloseProjectExecute()
{
     _projectManager.CloseAsync();
 }
```

I think a sample would be very nice since there is no projectmanagment in Orchestra or LogViewer.

Regards,
Michael

**Comment by GeertvanHorrik** [comment]
We believe it's best that the Project class (your own model) manages the IsDirty. This allows any view model / watcher to deal with this on its own.

**Comment by Orcomp** [comment]
You could also look at https://github.com/WildGums/CsvTextEditor for some inspiration. I don't think it implements IsDirty but it is probably closer to what you are trying to achieve
