### ISSUE TITLE
 Workflow with instantiating new projects

### ISSUE THREAD

**Issue by ArXen42** [WildGums/Orc.ProjectManagement#5]
If I understand correctly, `IProjectManager` is supposed to be the application's central projects repository (i.e. observable collection of the loaded projects, currently active project, etc). There are methods/events to load and save projects, however, I cannot see any (public) way to **register** arbitrary project instance (and there is also no "new" or "create" buttons in CsvTextEditor, for example) and it seems like SaveAsync in `ProjectManager` does not register project by itself (only `LoadAsync`).

Did I miss something or the only correct way to initialize new project consists of the following steps?

1. Create new instance of IProject.
2. Save it through `IProjectManager` to some location and "forget" about that instance.
3. Load new project from that location and use the resulting instance (which will be internally registered).

**Comment by mkhomutov** [comment]
you are absolutely correct
if you need to create new project, then just create new instance of your implementation of `IProject`, save it using `IProjectManager.SaveAsync()`
And if you want to immediately load this project, then just use `IProjectManager.LoadAsync()`

**Comment by ArXen42** [comment]
Thanks for the clarification, works perfectly
